name: Run Py label_generator

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Generate labels"

  pull_request:

jobs:
  generate_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Checkout repo content
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.head_ref_branch }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
        shell: bash

      - name: Execute py script
        id: generate_labels
        run: python .github/scripts/GenerateLabels.py
        shell: bash

      - run: echo ${{ steps.generate_labels.outputs.list_directory }}

    outputs:
      list_directory: ${{ steps.generate_labels.outputs.list_directory }}


  save_new_labels:
    runs-on: ubuntu-latest

    needs: generate_labels

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
        shell: bash

      - name: Pass Inputs to Shell
        run: |
          echo "INPUT_LIST=${{needs.generate_labels.outputs.list_directory}}" >> $GITHUB_ENV

      - name: Execute py script
        id: save_labels
        run: python .github/scripts/SaveNewLabels.py
        shell: bash

      - name: Check diff
        uses: technote-space/get-diff-action@v6
        with:
          FILES: |
            .github/labeler.yml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Bot: Update labeler.yml" -a
        if: env.GIT_DIFF && env.MATCHED_FILES

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        if: env.GIT_DIFF && env.MATCHED_FILES