name: Run Py label_generator

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:

  save_new_labels:
    runs-on: ubuntu-latest  
    environment: production
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
        shell: bash

      - name: Pass Inputs to Shell
        run: |
          echo "INPUT_LIST=${{needs.generate_labels.outputs.list_directory}}" >> $GITHUB_ENV

      - name: Execute py script
        id: save_labels
        run: python .github/scripts/SaveNewLabels.py
        shell: bash

      - name: Check diff
        uses: technote-space/get-diff-action@v6
        with:
          FILES: |
            .github/labeler.yml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Bot: Update labeler.yml" -a
        if: env.GIT_DIFF && env.MATCHED_FILES

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        if: env.GIT_DIFF && env.MATCHED_FILES
  


  